#!/usr/bin/env python3
"""Build bangs artifacts off the redirect path.

Reads src/bang.ts (source of truth, vendored) and generates:
  - src/generated/bangRedirect.ts  (redirect-only Map: tag -> [domain, urlTemplate])
  - public/data/bangs.min.json     (full list for /search + /blocklist: t,s,d,u only)
  - public/data/bangs-version.json ({version, count, ...} for versioned updates)

Redirect bundle drops c,r,sc (+s) so main.ts never parses display metadata.
Full JSON is fetched lazily and cached in IndexedDB + SW CacheFirst, so
deploys only cache-bust the tiny version file, not a 2MB JS chunk.

Usage: python3 scripts/build-bangs.py
"""
import hashlib
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "bang.ts"
OUT_TS = ROOT / "src" / "generated" / "bangRedirect.ts"
OUT_JSON = ROOT / "public" / "data" / "bangs.min.json"
OUT_VERSION = ROOT / "public" / "data" / "bangs-version.json"

# Matches one bang object block. Fields may appear in any order; string
# values are double-quoted except a handful of u fields with embedded
# double quotes, which use single quotes.
OBJ_RE = re.compile(r"\{[^{}]*?t:\s*[\"'](?:[^\"'\\]|\\.)*[\"'][^{}]*?\}", re.S)
STR_FIELD_RE_TEMPLATE = r"{key}\s*:\s*(?:\"((?:[^\"\\]|\\.)*)\"|'((?:[^'\\]|\\.)*)')"


def unescape_js_string(s: str, quote: str = '"') -> str:
    # JS string escapes here are a subset of JSON's; decode via json.
    # Single-quoted values may contain unescaped double quotes — escape
    # them before decoding, and unescape \' first.
    if quote == "'":
        s = s.replace("\\'", "\x01").replace('"', '\\"').replace("\x01", "'")
    return json.loads(f'"{s}"')


def parse_field(block: str, key: str) -> str:
    m = re.search(STR_FIELD_RE_TEMPLATE.format(key=re.escape(key)), block)
    if not m:
        return ""
    if m.group(1) is not None:
        return unescape_js_string(m.group(1), '"')
    return unescape_js_string(m.group(2), "'")


def main() -> int:
    text = SRC.read_text(encoding="utf-8")
    # Object bodies contain {{{s}}} triple braces; mask them so the
    # brace-balanced object regex can match one block at a time.
    masked = text.replace("{{{s}}}", "__BANG_S__")
    blocks = OBJ_RE.findall(masked)
    entries = []
    seen = set()
    for b in blocks:
        t = parse_field(b, "t")
        d = parse_field(b, "d").replace("__BANG_S__", "{{{s}}}")
        u = parse_field(b, "u").replace("__BANG_S__", "{{{s}}}")
        s = parse_field(b, "s").replace("__BANG_S__", "{{{s}}}")
        if not t or not u:
            continue
        key = t.lower()
        if key in seen:
            print(f"duplicate tag skipped: {t}", file=sys.stderr)
            continue
        seen.add(key)
        entries.append({"t": t, "s": s, "d": d, "u": u})

    if not entries:
        print("no bang entries parsed!", file=sys.stderr)
        return 1

    # Stable order for deterministic builds / diffs.
    entries.sort(key=lambda e: e["t"].lower())

    # Version = sha1 of canonical redirect payload (t|d|u per entry).
    h = hashlib.sha1()
    for e in entries:
        h.update(e["t"].lower().encode())
        h.update(b"\x00")
        h.update(e["d"].encode())
        h.update(b"\x00")
        h.update(e["u"].encode())
        h.update(b"\x00")
    version = h.hexdigest()[:12]

    # --- redirect-only TS module (tag -> url template, no metadata) ---
    # The root domain is derived from the template origin at runtime, so
    # d is dropped too: redirect bundle carries exactly one string per bang.
    OUT_TS.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// AUTO-GENERATED by scripts/build-bangs.py — do not edit.",
        f"// source: src/bang.ts ({len(entries)} entries, version {version})",
        "// Redirect-only map: lowercase tag -> url template.",
        "// Drops c/r/sc/s/d so the redirect path parses the minimum.",
        f'export const BANG_VERSION = "{version}";',
        "export const redirectMap: Record<string, string> = {",
    ]
    for e in entries:
        key = json.dumps(e["t"].lower(), ensure_ascii=False)
        val = json.dumps(e["u"], ensure_ascii=False)
        lines.append(f"{key}:{val},")
    lines.append("};\n")
    OUT_TS.write_text("\n".join(lines), encoding="utf-8")

    # --- full compressed JSON for search/blocklist (t,s,d,u only) ---
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(
        json.dumps(entries, ensure_ascii=False, separators=(",", ":")),
        encoding="utf-8",
    )

    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    OUT_VERSION.write_text(
        json.dumps(
            {
                "version": version,
                "count": len(entries),
                "generatedAt": generated_at,
                "dataUrl": "data/bangs.min.json",
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    ts_bytes = OUT_TS.stat().st_size
    json_bytes = OUT_JSON.stat().st_size
    src_bytes = SRC.stat().st_size
    print(f"entries: {len(entries)}  version: {version}")
    print(f"src/bang.ts: {src_bytes/1e6:.2f}MB -> redirect TS: {ts_bytes/1e6:.2f}MB, json: {json_bytes/1e6:.2f}MB")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
